version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "7080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ~/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    image: jenkins/ssh-agent:jdk17
    container_name: agent
    user: root
    ports:
      - "2222:22"  # Avoid conflict with host SSH
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKKdjIf/t/5IaFAEmVUoDSx0++NirIxqhM+Dsg99sqMz manhhung20033004@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    external: true